import { build } from "esbuild";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFile } from "node:fs/promises";

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, "../../Sources/Clonie/Resources/MarkdownEditor.swift");

const result = await build({
  entryPoints: [resolve(here, "editor.mjs")],
  bundle: true,
  write: false,
  format: "iife",
  globalName: "ClonieMarkdownEditorBundle",
  target: ["safari17"],
  minify: true,
  legalComments: "none",
  charset: "utf8"
});

const bundled = result.outputFiles[0].text.trim();
const javascript = [
  "var ClonieMarkdownEditor=(function(document){",
  bundled,
  "return ClonieMarkdownEditorBundle;",
  "})(typeof document===\"object\"&&document.documentElement&&document.documentElement.style?document:undefined);"
].join("");
if (!javascript.startsWith("var ClonieMarkdownEditor=")) {
  throw new Error("The editor bundle did not produce the expected IIFE global");
}
if (/<\/script/i.test(javascript)) {
  throw new Error("The editor bundle contains a raw closing script tag");
}

// This also proves importing the bundle does not require a browser global.
const api = new Function(`${javascript};return ClonieMarkdownEditor;`)();
for (const name of ["mount", "destroyAll", "destroyDetached", "reset", "links", "performHistory"]) {
  if (typeof api[name] !== "function") {
    throw new Error(`Missing editor API: ${name}`);
  }
}
const linkProbe = api.links(
  "[문서](notes/source.md) ![그림](image.png) `[가짜](code.md)`\n\n[참조][id]\n\n[id]: ref.md"
);
if (linkProbe.length !== 1 || linkProbe[0].label !== "문서" ||
    linkProbe[0].target !== "notes/source.md") {
  throw new Error("The generated link API did not preserve the parser-based inline-link boundary");
}
if (api.performHistory("undo") !== false) {
  throw new Error("The history API claimed an editor without a focused DOM mount");
}
const stubAPI = new Function(
  "document",
  `${javascript};return ClonieMarkdownEditor;`
)({ getElementById() { return null; } });
if (stubAPI.mount(null) !== null) {
  throw new Error("The editor did not preserve its no-DOM mount fallback");
}

let hashes = 1;
while (javascript.includes(`\"\"\"${"#".repeat(hashes)}`)) hashes += 1;
const delimiter = "#".repeat(hashes);
const swift = `// Generated by scripts/markdown-editor/build.mjs. Do not edit by hand.\n\nimport Foundation\n\nfunc markdownEditorJavaScript() -> String {\n    return ${delimiter}\"\"\"\n${javascript}\n\"\"\"${delimiter}\n}\n`;

await writeFile(output, swift);
console.log(`Wrote ${output} (${javascript.length} JavaScript bytes)`);
